#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 14, 2018 06:37:19 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import proyecto_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    proyecto_support.set_Tk_var()
    top = APP (root)
    proyecto_support.init(root, top)
    root.mainloop()

w = None
def create_APP(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    proyecto_support.set_Tk_var()
    top = APP (w)
    proyecto_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_APP():
    global w
    w.destroy()
    w = None


class APP:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1002x721+349+169")
        top.title("APP")
        top.configure(highlightcolor="black")



        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.01, relheight=0.96, relwidth=0.98)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(width=985)

        self.Entry2 = Entry(self.Frame1)
        self.Entry2.place(relx=0.29, rely=0.13,height=23, relwidth=0.17)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(justify=CENTER)
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(textvariable=proyecto_support.entry2)

        self.TCombobox1 = ttk.Combobox(self.Frame1)
        self.TCombobox1.place(relx=0.29, rely=0.22, relheight=0.03
                , relwidth=0.17)
        self.value_list = ['Papa','Yuca','Cafe',]
        self.TCombobox1.configure(values=self.value_list)
        self.TCombobox1.configure(justify=CENTER)
        READONLY = 'readonly'
        self.TCombobox1.configure(state=READONLY)
        self.TCombobox1.configure(textvariable=proyecto_support.combo2)
        self.TCombobox1.configure(takefocus="")

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.02, rely=0.09, height=21, width=206)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Ingrese el Valor de la Inversión''')

        self.Label2 = Label(self.Frame1)
        self.Label2.place(relx=0.02, rely=0.13, height=21, width=214)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''Ingrese el Número de Hectareas''')

        self.Label3 = Label(self.Frame1)
        self.Label3.place(relx=0.02, rely=0.17, height=21, width=170)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''Ingrese el Mes a Sembrar''')

        self.Label4 = Label(self.Frame1)
        self.Label4.place(relx=0.02, rely=0.22, height=21, width=100)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''Tipo de cultivo''')

        self.TButton1 = ttk.Button(self.Frame1)
        self.TButton1.place(relx=0.15, rely=0.39, height=28, width=163)
        self.TButton1.configure(command=proyecto_support.calcular)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Enviar''')

        self.Label5 = Label(self.Frame1)
        self.Label5.place(relx=0.28, rely=0.03, height=21, width=498)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(text='''BIENVENIDO A NUESTRA APP, DONDE APRENDERÁ MÁS SOBRE SU CULTIVO''')

        self.Label6 = Label(self.Frame1)
        self.Label6.place(relx=0.03, rely=0.58, height=21, width=87)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(text='''RESULTADO:''')

        self.Label7 = Label(self.Frame1)
        self.Label7.place(relx=0.03, rely=0.68, height=21, width=108)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(text='''Precio Esperado''')

        self.Label8 = Label(self.Frame1)
        self.Label8.place(relx=0.03, rely=0.73, height=21, width=139)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(text='''Producción Esperada''')

        self.Entry1 = Entry(self.Frame1)
        self.Entry1.place(relx=0.29, rely=0.09,height=23, relwidth=0.17)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(justify=CENTER)
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(textvariable=proyecto_support.entry1)

        self.Label9 = Label(self.Frame1)
        self.Label9.place(relx=0.29, rely=0.68, height=21, width=159)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(background="#ffffff")
        self.Label9.configure(textvariable=proyecto_support.precio)

        self.Label10 = Label(self.Frame1)
        self.Label10.place(relx=0.29, rely=0.73, height=21, width=159)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(background="#ffffff")
        self.Label10.configure(textvariable=proyecto_support.prod)

        self.Label11 = Label(self.Frame1)
        self.Label11.place(relx=0.48, rely=0.52, height=311, width=489)
        self.Label11.configure(activebackground="#f9f9f9")
        self.Label11.configure(background="#ffffff")

        self.Map = Label(self.Frame1)
        self.Map.place(relx=0.48, rely=0.09, height=281, width=489)
        self.Map.configure(activebackground="#f9f9f9")
        self.Map.configure(background="#ffffff")
        self.Map.configure(borderwidth="3")
        self.Map.configure(compound="center")
        self._img1 = PhotoImage(file="./mapa.png")
        self.Map.configure(image=self._img1)

        self.Button1 = Button(self.Frame1)
        self.Button1.place(relx=0.15, rely=0.83, height=29, width=159)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(command=proyecto_support.destroy_window)
        self.Button1.configure(text='''Salir''')

        self.TCombobox2 = ttk.Combobox(self.Frame1)
        self.TCombobox2.place(relx=0.29, rely=0.17, relheight=0.03
                , relwidth=0.17)
        self.value_list = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre',]
        self.TCombobox2.configure(values=self.value_list)
        self.TCombobox2.configure(justify=CENTER)
        READONLY = 'readonly'
        self.TCombobox2.configure(state=READONLY)
        self.TCombobox2.configure(textvariable=proyecto_support.combo1)
        self.TCombobox2.configure(foreground="#000000")
        self.TCombobox2.configure(background="#ffffff")
        self.TCombobox2.configure(takefocus="")

        self.Label12 = Label(self.Frame1)
        self.Label12.place(relx=0.29, rely=0.68, height=21, width=12)
        self.Label12.configure(activebackground="#f9f9f9")
        self.Label12.configure(background="#ffffff")
        self.Label12.configure(text='''$''')






if __name__ == '__main__':
    vp_start_gui()



